/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"
#include <stdio.h>
//#include <string.h> 

int bin_cnv(int n){
	int i = 0,a[64],m,rslt,k = 1;
    for(i=0; n>0; i++){    
		a[i]=n%2;    
		n = n/2;  
	}      
	m = i;
	for(i=0 ;i<m ;i++){    
		rslt += a[i]*k;
		k *= 10;    
	}    
	return rslt;
}
int power(int a,int b){
	int k = 1;
	if (b == 0){
		return 1;
	}else{
		int i = 0;
		for( i = 0; i < b;i++){
			k *= a; 
		}	
	}
	return k;
}


char decToHexa(int n)
{
    char hexaDeciNum[100];
    char result[100];
    int i = 0;
    while (n != 0) {
        int temp = 0;
        temp = n % 16;
        if (temp < 10) {
            hexaDeciNum[i] = temp + 48;
            i++;
        }
        else {
            hexaDeciNum[i] = temp + 55;
            i++;
        }
 
        n = n / 16;
    }
    for (int j = i - 1; j >= 0; j--)
        result[i - j + 1] = hexaDeciNum[j];
	return result;
}

void *
calnull_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	//printf ("Pong\n");fflush (stdout);

	return (void *) &result;
}

long *
puiss_1_svc(Param *argp, struct svc_req *rqstp)
{
	static long  result;

	result = power(argp->x,argp->pui);

	return &result;
}

long *
dec2bin_1_svc(int *argp, struct svc_req *rqstp)
{
	static long  result;

	result = bin_cnv(*argp);

	return &result;
}

char *
dec2hex_2_svc(int *argp, struct svc_req *rqstp)
{
	static char  result;

	result = decToHexa(*argp);

	return &result;
}
